# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/azure-functions-extension-base"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    # Files stored in `app` directory
    directory: "/azure-functions-extension-fastapi"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    # Files stored in `app` directory
    directory: "/azure-functions-extension-blob"
    schedule:
      interval: "weekly"
