# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from azurefunctions.extensions.bindings.protos import settlement_pb2 as azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in azurefunctions/extensions/bindings/protos/settlement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SettlementStub(object):
    """The settlement service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/Settlement/Complete',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.CompleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Abandon = channel.unary_unary(
                '/Settlement/Abandon',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.AbandonRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Deadletter = channel.unary_unary(
                '/Settlement/Deadletter',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeadletterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Defer = channel.unary_unary(
                '/Settlement/Defer',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeferRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RenewMessageLock = channel.unary_unary(
                '/Settlement/RenewMessageLock',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewMessageLockRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSessionState = channel.unary_unary(
                '/Settlement/GetSessionState',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateRequest.SerializeToString,
                response_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateResponse.FromString,
                _registered_method=True)
        self.SetSessionState = channel.unary_unary(
                '/Settlement/SetSessionState',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.SetSessionStateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ReleaseSession = channel.unary_unary(
                '/Settlement/ReleaseSession',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.ReleaseSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RenewSessionLock = channel.unary_unary(
                '/Settlement/RenewSessionLock',
                request_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockRequest.SerializeToString,
                response_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockResponse.FromString,
                _registered_method=True)


class SettlementServicer(object):
    """The settlement service definition.
    """

    def Complete(self, request, context):
        """Completes a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abandon(self, request, context):
        """Abandons a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deadletter(self, request, context):
        """Deadletters a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Defer(self, request, context):
        """Defers a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewMessageLock(self, request, context):
        """Renew message lock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionState(self, request, context):
        """Get session state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionState(self, request, context):
        """Set session state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSession(self, request, context):
        """Release session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewSessionLock(self, request, context):
        """Renew session lock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettlementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.CompleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Abandon': grpc.unary_unary_rpc_method_handler(
                    servicer.Abandon,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.AbandonRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Deadletter': grpc.unary_unary_rpc_method_handler(
                    servicer.Deadletter,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeadletterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Defer': grpc.unary_unary_rpc_method_handler(
                    servicer.Defer,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeferRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RenewMessageLock': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewMessageLock,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewMessageLockRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionState,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateRequest.FromString,
                    response_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateResponse.SerializeToString,
            ),
            'SetSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionState,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.SetSessionStateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReleaseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSession,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.ReleaseSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RenewSessionLock': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewSessionLock,
                    request_deserializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockRequest.FromString,
                    response_serializer=azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Settlement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Settlement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Settlement(object):
    """The settlement service definition.
    """

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/Complete',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.CompleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abandon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/Abandon',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.AbandonRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deadletter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/Deadletter',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeadletterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Defer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/Defer',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.DeferRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewMessageLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/RenewMessageLock',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewMessageLockRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/GetSessionState',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateRequest.SerializeToString,
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.GetSessionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/SetSessionState',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.SetSessionStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/ReleaseSession',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.ReleaseSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewSessionLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Settlement/RenewSessionLock',
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockRequest.SerializeToString,
            azurefunctions_dot_extensions_dot_bindings_dot_protos_dot_settlement__pb2.RenewSessionLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
