jobs:
  - job: "TestPython"
    displayName: "Run Extension Unit Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        base-38:
          PYTHON_VERSION: '3.8'
          EXTENSION_DIRECTORY: 'azurefunctions-extensions-base'
