name: UT CI Run for Python Extension Blob

on:
    push:
      branches: [ dev, master, main, release/* ]
      paths:
        - 'azure-functions-extension-base/**'
        - 'azure-functions-extension-blob/**'
    pull_request:
        branches: [ dev, master, main, release/* ]
        paths:
          - 'azure-functions-extension-base/**'
          - 'azure-functions-extension-blob/**'

jobs:
  build:
    name: "Python Extension UT CI Run"
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: [ 3.9, "3.10", "3.11" ]
    permissions: read-all
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: azure-functions-extension-blob
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U -e .[dev]
        python -m pip install -e ../azure-functions-extension-base

    - name: Run Unit Tests
      working-directory: azure-functions-extension-blob
      run: |
        python -m pytest -q --instafail --cov=. --cov-report xml --cov-branch tests

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./azure-functions-extension-blob/coverage.xml
        flags: unittests
        name: codecov
        fail_ci_if_error: false

    - name: Notify dedicated teams channel
      uses: jdcargile/ms-teams-notification@v1.4
      if: failure()
      with:
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "Python Extension Blob UT CI Failed for Python ${{ matrix.python-version }}"
        notification-color: 17a2b8
        timezone: America/Denver
        verbose-logging: false
