name: CI Run for Python Extension Base

on:
  push:
    branches:
      - dev
      - main
      - release/*
    paths:
      - 'azure-functions-extension-base/**'
  pull_request:
    branches:
      - dev
      - main
      - release/*
    paths:
      - 'azure-functions-extension-base/**'

jobs:
  build:
    name: "Python Extension Base CI Run"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
    permissions: read-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: azure-functions-extension-base
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -e .[dev]

      - name: Run Unit Tests
        working-directory: azure-functions-extension-base
        env:
          AzureWebJobsStorage: ${{ secrets.AzureWebJobsStorage }}
        run: |
          python -m pytest -q --instafail --cov=. --cov-report xml --cov-branch --ignore tests/ tests

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./azure-functions-extension-base/coverage.xml
          flags: unittests
          name: codecov
          fail_ci_if_error: false
          # TODO: upgrade to v4 when it is not breaking https://github.com/codecov/codecov-action/issues/1336
          # codecov_yml_path: .github/codecov/.codecov_base.yml

  send-notification:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Notify dedicated teams channel on failure
        if: ${{ always() && needs.build.result == 'failure' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Base CI Failed"
          notification-color: FF0000
          timezone: America/Denver
          verbose-logging: false

      - name: Notify dedicated teams channel on success
        if: ${{ always() && needs.build.result == 'success' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Base CI Passed"
          notification-color: 008000
          timezone: America/Denver
          verbose-logging: false
        