---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################

name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - 'release/*'
  pull_request:
    branches:
      - dev
      - main
      - 'release/*'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions: read-all

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          # VALIDATE_PYTHON_FLAKE8: false
          # VALIDATE_PYTHON_PYLINT: false # disable pylint, as we have not configure it
          VALIDATE_PYTHON_BLACK: true # same as above
          VALIDATE_PYTHON_ISORT: true # same as above
          PYTHON_BLACK_CONFIG_FILE: .isort.cfg
          PYTHON_ISORT_CONFIG_FILE: .isort.cfg
          # PYTHON_FLAKE8_CONFIG_FILE: tox.ini
          # FILTER_REGEX_INCLUDE: '^(azure-functions-extension-[^/]+/).*'
          # FILTER_REGEX_EXCLUDE: '^(azure-functions-extension-[^/]+/tests/).*'          
          DEFAULT_BRANCH: dev

  send-notification:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Notify dedicated teams channel on failure
        if: ${{ always() && needs.build.result == 'failure' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Linter CI Failed"
          notification-color: FF0000
          timezone: America/Denver
          verbose-logging: false

      - name: Notify dedicated teams channel on success
        if: ${{ always() && needs.build.result == 'success' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Linter CI Passed"
          notification-color: 008000
          timezone: America/Denver
          verbose-logging: false