---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################

name: Lint azurefunctions-extensions-bindings-blob

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - 'release/*'
    paths:
      - 'azurefunctions-extensions-bindings-blob/**'
  pull_request:
    branches:
      - dev
      - main
      - 'release/*'
    paths:
      - 'azurefunctions-extensions-bindings-blob/**'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint azurefunctions-extensions-bindings-blob
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: read
      packages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true # same as above
#          VALIDATE_PYTHON_ISORT: true # same as above TODO: fix conflicting linters
          PYTHON_ISORT_CONFIG_FILE: .isort.cfg
          FILTER_REGEX_INCLUDE: azurefunctions-extensions-bindings-blob/*
          DEFAULT_BRANCH: origin/dev
