---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################

name: Lint azurefunctions-extension-base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - 'release/*'
    paths:
      - 'azurefunctions-extension-base/**'
  pull_request:
    branches:
      - dev
      - main
      - 'release/*'
    paths:
      - 'azurefunctions-extension-base/**'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint azurefunctions-extension-base
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: read
      packages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true # same as above
          VALIDATE_PYTHON_ISORT: true # same as above
          PYTHON_ISORT_CONFIG_FILE: .isort.cfg
          FILTER_REGEX_INCLUDE: azurefunctions-extension-base/.*      
          DEFAULT_BRANCH: origin/dev

  send-notification:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Notify dedicated teams channel on failure
        if: ${{ always() && needs.build.result == 'failure' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Lint azurefunctions-extension-base Failed"
          notification-color: FF0000
          timezone: America/Denver
          verbose-logging: false

      - name: Notify dedicated teams channel on success
        if: ${{ always() && needs.build.result == 'success' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Python Extension Lint azurefunctions-extension-base Passed"
          notification-color: 008000
          timezone: America/Denver
          verbose-logging: false