name: PRs reviews reminder

on:
  # schedule:
    # Every weekday every 2 hours during working hours, send notification
    # - cron: "0 8-17/2 * * 1-5"
  workflow_dispatch:

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v2.7.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: '${{ secrets.MS_TEAMS_WEBHOOK_URI }}' # Required
        provider: 'msteams' # Required (slack, rocket or msteams)
        channel: '' # Optional, eg: #general
        github-provider-map: '${{ secrets.PR_REMINDER_USER_MAPPING }}' # Optional, eg: DavideViolante:UEABCDEFG,foobar:UAABCDEFG
        ignore-label: '' # Optional, eg: no-reminder,ignore me